global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 30s
    metrics_path: "/metrics"
    scheme: http
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'bootnode'
    scrape_timeout: 5s
    honor_labels: true
    metrics_path: "/debug/metrics/prometheus"
    scheme: http
    static_configs:
      - targets: [bootnode:6060]
